spring:
  profiles:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:8806/batch?useUnicode=true&characterEncoding=utf8
      username: root
      password: password!
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    job:
      enabled: true
#      names: job1, job2 # 이런식으로 job의 종류를 나열 할 수 있음.
    jdbc:
      initialize-schema: always
